port: 8081
download_path: https://s3.amazonaws.com/cloudify-training-resources/labs/apache-tomcat-7.0.82.tar.gz
war_url: https://s3.amazonaws.com/cloudify-training-resources/labs/helloworld.war
war_filename: helloworld.war
java_url: https://s3.amazonaws.com/cloudify-training-resources/labs/jdk-8u151-linux-x64.tar.gz
install_agent: false
vm_ip_address: 127.0.0.1
application_name: helloworld
