tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.0.0/types.yaml
  - plugin:cloudify-ansible-plugin

inputs:

  ip:
    type: string
    description: The VM IP.

  username:
    type: string
    description: The VM SSH user.
    default: centos

  private_key:
    type: string
    description: Full path to the VM's private key.
    default: /etc/cloudify/cfy-training.pem


node_templates:

  executor:
    type: cloudify.nodes.ansible.Executor
    properties:
      playbook_path: playbooks/start.yaml
      sources: &sources
        all:
          hosts:
            web:
              ansible_host: { get_input: ip }
              ansible_user: { get_input: username }
              ansible_ssh_private_key_file: { get_input: private_key }
              ansible_become: True
              ansible_ssh_common_args: -o StrictHostKeyChecking=no
      run_data:
        IP: { get_input: ip }
    interfaces:
      cloudify.interfaces.lifecycle:
        stop:
          implementation: ansible.cloudify_ansible.tasks.run
          inputs:
            playbook_path: playbooks/stop.yaml
            sources: *sources
