---
- name: Install nginx
  hosts: all
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: Insert Index Page
    template:
      src: ./files/index.html
      dest: /usr/share/nginx/html/index.html
  - name: Start NGiNX
    service:
      name: nginx
      state: started