---
# These tasks install http and the php modules.

#- name: Install http and php etc
#  yum: name={{ item }} state=present
#  with_items:
#   - httpd
#   - php
#   - php-mysql
#   - git
#   - libsemanage-python
#   - libselinux-python

- name: Install httpd
  yum: name=httpd state=present

- name: Install php
  yum: name=php state=present

- name: Install php-mysql
  yum: name=php-mysql state=present

- name: Install git
  yum: name=git state=present

- name: Install libsemanage-python
  yum: name=libsemanage-python state=present

- name: Install mariadb
  yum: name=libselinux-python state=present

# - name: insert iptables rule for httpd
#   lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#               line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#   notify: restart iptables

- firewalld:
    port: "{{ httpd_port }}/tcp"
    permanent: yes
    state: enabled

- name: http service state
  service: name=httpd state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0
