tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.0.0/types.yaml
  - plugin:cloudify-ansible-plugin

inputs:

  ip:
    type: string
    description: The VM IP.

  username:
    type: string
    description: The VM SSH user.
    default: centos

  private_key:
    type: string
    description: Full path to the VM's private key.
    default: /etc/cloudify/cfy-training.pem


node_templates:

  vm:
    type: cloudify.nodes.Compute
    properties:
      ip: { get_input: ip }
      agent_config:
        install_method: none
        user: { get_input: username }
        key: { get_input: private_key }
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: ansible.cloudify_ansible.tasks.run
          inputs:
            playbook_path: playbooks/start.yaml
            sources: &sources
              all:
                hosts:
                  web:
                    ansible_host: { get_property: [SELF, ip] }
                    ansible_user: { get_property: [SELF, agent_config, user] }
                    ansible_ssh_private_key_file: { get_property: [SELF, agent_config, key] }
                    ansible_become: True
                    ansible_ssh_common_args: -o StrictHostKeyChecking=no
        stop:
          implementation: ansible.cloudify_ansible.tasks.run
          inputs:
            playbook_path: playbooks/stop.yaml
            sources: *sources
